### ISSUE TITLE
Id generation default for AuditLogEvent should align with GORM default.

### ISSUE THREAD

**Issue by kastone** [robertoschwald/grails-audit-logging-plugin#100]
As a result of https://jira.grails.org/browse/GPAUDITLOGGING-29 in the 1.0.4 and greater version of the plugin, the default id generation for audit_log table is set to 'increment' by default. The default behavior in Grails is 'native'. I had upgraded the plugin and using it out of the box with this change and SqlServer caused the insertion of audit_log records to fail with the following error. 
ERROR spi.SqlExceptionHelper  - Cannot insert explicit value for identity column in table 'audit_log' when IDENTITY_INSERT is set to OFF.

ERROR auditable.AuditLogListener  - Failed to create AuditLogEvent for audit log Fri Aug 07 10:29:22 EDT 2015 user system INSERT Address id:6 version:0: Hibernate operation: could not execute statement; SQL [n/a]; Cannot insert explicit value for identity column in table 'audit_log' when IDENTITY_INSERT is set to OFF.; nested exception is java.sql.SQLException: Cannot insert explicit value for identity column in table 'audit_log' when IDENTITY_INSERT is set to OFF.`

Relevant Code AuditLogEvent.groovy:
`// GPAUDITLOGGING-29 support configurable id mapping for AuditLogEvent
        if (Holders.config.auditLog.idMapping) {
          def map = Holders.config.auditLog.idMapping
          id generator:map.generator, type:map.type, length:map.length
        } else {
          id generator:'increment', type:'long' // default
        }`

When I explicitly defined for plugin to use native generation in Config.groovy, it worked as expected. The plugin should use the same default generation as GORM. Otherwise the documentation should be clearer that the developer needs to configure this to match default behavior of GORM.

`auditLog{
    idMapping = [generator:"native", type:"long"]//Grails default is native
}`

**Comment by robertoschwald** [comment]
Thank you.
Will fix with next snapshot iteration

**Comment by robertoschwald** [comment]
Fixed with latest published 1.0.6-SNAPSHOT version.
