### ISSUE TITLE
Doesnt work with mysql & Galera Cluster

### ISSUE THREAD

**Issue by SimonHobbsNektan** [robertoschwald/grails-audit-logging-plugin#102]
auto-increment fields work slightly differently with galera cluster.  If there are say 3 mysql nodes in the cluster, the first node will give id=1, id=4 etc. On cluster 2, inserts on node 2 will get Id=2, id=5 etc.

i.e. there are holes in the sequences (or it appears that way to the app.

Our code works fine on a single server, but as soon as we put it on galera cluster, the audit stuff fails, with this kind of error:

2015-08-28 16:52:51,492 auditable.AuditLogListener: Failed to create AuditLogEvent for audit log Fri Aug 28 16:52:51 BST 2015 user system UPDATE Operator id:2 version:28: Hibernate operation: could not execute statement; SQL [n/a]; Duplicate entry '277' for key 'PRIMARY'; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '277' for key 'PRIMARY'

Looking at the audit plugin, there is no auto-increment on the ID field. how does it generage its ID sequence?

**Comment by robertoschwald** [comment]
It uses the standard gorm id mapping.
Take a look at AuditLogEvent domain class in the plugin:

```java
    if (Holders.config.auditLog.idMapping) {
          def map = Holders.config.auditLog.idMapping
          id generator:map.generator, type:map.type, length:map.length
        } else {
          id generator:'increment', type:'long' // default
   }
```

You can configure the id mapping in Config.groovy, e.g.

    auditLog  {
        idMapping = [generator:"uuid2", type:"string", length:36] // UUID id-type for AuditLogEvent
    }

We will switch the default id mapping to "native" in the next minor 1.x release. See #100

For now, you can change it yourselve and try again. 

Source see https://github.com/robertoschwald/grails-audit-logging-plugin/blob/1.x_maintenance/grails-audit-logging-plugin/grails-app/domain/org/codehaus/groovy/grails/plugins/orm/auditable/AuditLogEvent.groovy

**Comment by SimonHobbsNektan** [comment]
Hi, i dont think either of these strategies will work with a cluster. Is there no way to use a simple auto-increment Id field instead of generating the ID in the code, which cant know what other members of the cluster are doing?
