### ISSUE TITLE
Plugin only logging inserts with MongoDB as only Database

### ISSUE THREAD

**Issue by bronoman** [robertoschwald/grails-audit-logging-plugin#103]
Hi,
I just noticed that audit logging plugin 1.0.6 apparently **does not log changes / updates** when using MongoDB. Inserts are logged fine and are shown in the database collection, both from bootstrap and from controller.

*Environment:*
Grails 2.4.4
MongoDB GORM 3.0.3
Audit-Logging 1.0.6
DB: MongoDB 2.6.10

**Comment by robertoschwald** [comment]
Fixed a problem with the MongoDB plugin for dirty properties. The MongoDB plugin adds the domain class name to the set of dirty properties on update. Seems to be a bug in their plugin.

Audit-Logging now filters domain names from the dirty property name map. 

Please try version 1.1.0-SNAPSHOT (You must perform grails audit-quickstart <domainname> to get the AuditLogEvent domain created into your project)

It might be possible that we release version 1.0.7 with backported fix for this problem.

**Comment by robertoschwald** [comment]
See also the example projects we just created:

MongoDB sample:
 
https://github.com/robertoschwald/grails-audit-logging-plugin-examples/tree/mongoDbOnlyDatasource

Hibernate sample:

https://github.com/robertoschwald/grails-audit-logging-plugin-examples

**Comment by bronoman** [comment]
Thanks for the new SNAPSHOT and the MongoDB sample link. Extremely helpful. Looks like there is still a minor problem with the **audit-quickstart** script, the stacktrace is:

> | Error Error executing script AuditQuickstart: org/codehaus/groovy/grails/plugins/orm/auditable/AuditLoggingUtils (NOTE: Stack trace has been filtered.[...]
 trace.)
**java.lang.NoClassDefFoundError: org/codehaus/groovy/grails/plugins/orm/auditable/AuditLoggingUtils**
        at AuditQuickstart$_updateConfig_closure2.doCall(AuditQuickstart:90)
        at AuditQuickstart.updateConfig(AuditQuickstart:86)
        at AuditQuickstart.this$4$updateConfig(AuditQuickstart)
        at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
        at [...........]

However, after adding the new config parameter manually to my Config.groovy like:
**``` auditDomainClassName = "com.example.myApp.AuditLogEvent" ```**
my application started up correctly and the external domain class seems to work fine.

But: still no UPDATES are logged... INSERTS can be seen fine in the MongoDB collection fine as before. Any ideas?

**Comment by robertoschwald** [comment]
Thanks for the report about AuditLoggingUtils problem. Will look into it.

Have you tried the sample MongDB-Only Application locally? 
https://github.com/robertoschwald/grails-audit-logging-plugin-examples/tree/mongoDbOnlyDatasource

There, all CRUD operations are logged in my case. Just start it and e.g. add / update / delete a book entry. Maybe a hint to find out what happens. 

If you are using IDEA / Eclipse in your project, set a breakpoint to AuditLogListener Line 90:
 
    if (event.source != this.datastore)

or enable trace logging for "org.codehaus.groovy.grails.plugins.orm.auditable".

**Comment by bronoman** [comment]
Hi, just tried the MongoDB-Only application here locally. It works. Thanks for the debug hints. I need to dig into my application, now..

**Comment by robertoschwald** [comment]
Opened issue report in mongodb plugin for this: https://github.com/grails/grails-data-mapping/issues/560

**Comment by robertoschwald** [comment]
1.1.0-SNAPSHOT2 fixes the reported AuditLoggingUtils problem as well.
