### ISSUE TITLE
whitelist properties instead of blacklist (ignore)

### ISSUE THREAD

**Issue by phibo23** [robertoschwald/grails-audit-logging-plugin#113]
It would be nice to have an option to specify which fields should be logged instead of which ones should not. This would make it easier to avoid unintended logging in case of new properties being introduced after the initial logging configuration.

**Comment by svetozar02** [comment]
+1

**Comment by robertoschwald** [comment]
PR welcome.

**Comment by ryanduffyegov** [comment]
Agreed +1

**Comment by ptaylor** [comment]
Suggested implementation in #138

**Comment by robertoschwald** [comment]
Will release 1.1.3-SNAPSHOT with this functionality, so we can test in real as well before we release.

**Comment by robertoschwald** [comment]
1.1.3-SNAPSHOT is published. Please test in your project(s).

**Comment by ptaylor** [comment]
I've testing 1.1.3-SNAPSHOT and it works for me.  Thanks!

**Comment by phibo23** [comment]
great to see this was implemented. Unfortunately, I'm not involved in the project anymore where I wanted this feature, so I won't be able to check if it now meets my requirements. However, the code from the PR looks good to me. I'd say you can close this issue when the new settings are described in the documentation.

**Comment by robertoschwald** [comment]
This feature is documented now on https://grails.org/plugin/audit-logging?skipRedirect=true
