### ISSUE TITLE
unclean build of 2.0.0 published?

### ISSUE THREAD

**Issue by rvanderwerf** [robertoschwald/grails-audit-logging-plugin#117]
So we're seeing this plugin run inproperly as a war on Tomcat 8.  The method GrailsAppServletInitializer.createRootApplicationContext is being called bug the plugin and it shouldn't have an ApplicationLoader in it. We've found this can be an issue if you use IntelliJ's compiler without a clean before making a jar/package-plugin file. I'll fork it and make a clean build to if that fixes or something else is going on and report back. (This is in Grails 3.0.11).

**Comment by atreides322** [comment]
I am actually running into a variation of this issue. I was having weird interactions between audit-logging and an internal Spring Security provider plugin, when deploying an app as a war in Tomcat 7. I was seeing that the Grails app was getting initialized twice. The second intialization was throwing an NPE when trying to find a controller artefact by classname. If I rebuild the jar from the 2.0.0 tag, it generates a very different jar, an executable jar, but this class isn't present and the war loads just fine.

**Comment by robertoschwald** [comment]
please try 2.0.1-SNAPSHOT

**Comment by atreides322** [comment]
This works for me.

**Comment by robertoschwald** [comment]
2.0.1 is released.
