### ISSUE TITLE
Injection of autowired dependencies failed

### ISSUE THREAD

**Issue by betsonc** [robertoschwald/grails-audit-logging-plugin#119]
Hi, using Grails 3.1.4 and audit-logging:2.0.1 I get the error below
We use application.yml if this makes a difference. Can we have application.yml and application.groovy together?

Any ideas what is causing it? 
Many Thanks

Error creating bean with name 'grails.plugins.orm.auditable.AuditLogEventController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException:

Could not autowire method: public void grails.plugins.orm.auditable.AuditLogEventController.setTagLibraryLookup(org.grails.taglib.TagLibraryLookup); 
nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No qualifying bean of type [org.grails.taglib.TagLibraryLookup] found for dependency: 
expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}

**Comment by robertoschwald** [comment]
As written offline to you, we never saw this problem.
I created a simple Grails 3.1.4 sample application on https://github.com/robertoschwald/grails-audit-logging-plugin-examples/tree/grails_3.1.4

In Bootstrap.groovy, it creates / deletes an example Domain entity and log out the auditlog contents. No problem here. Please check.

**Comment by kowsercse** [comment]
Adding the gsp plugin dependency fixes the issue.

`compile "org.grails:grails-plugin-gsp"`
For more https://github.com/grails-plugins/grails-spring-security-core/issues/379

@robertoschwald Is it possible to add this dependency in the plugin.

**Comment by robertoschwald** [comment]
yes, will do.
