### ISSUE TITLE
Configure plugin to capture all items in oldMap and newMap on update events

### ISSUE THREAD

**Issue by dmahapatro** [robertoschwald/grails-audit-logging-plugin#12]
Plugin can be enhanced to capture all the properties (instead of just the dirty and recently updated properties) of a domain object in `oldMap` and `newMap` in `onChange` event based on a config option (say, `captureAllOnUpdate=true`). 

By doing so we get access to all of the items in both the maps which can be referred down the lane. This is mainly helpful with `handlersOnly` configuration. Thoughts? @robertoschwald

**Comment by robertoschwald** [comment]
Good idea. But then we should check if handlersOnly is set, otherwise do not log, as this would fill the db table quickly with unneeded entries.

**Comment by dmahapatro** [comment]
Agree.

**Comment by robertoschwald** [comment]
As we will remove the handler support, soon, I close this issue.
