### ISSUE TITLE
Filter auditLogs by time

### ISSUE THREAD

**Issue by Misenooooo** [robertoschwald/grails-audit-logging-plugin#123]
I want to use your plugin in my application in the administration interface, but I can't filter your logs by time, because createdAt field and lastUpdated are instances of class Date. 

Could you change it?

I am quite new to grails, so if you know some way, how to filter it by date and time, please let me know. I tried to use criteria, but I managed to filter it only by date.

**Comment by robertoschwald** [comment]
Which plugin version?

**Comment by Misenooooo** [comment]
I am using 'org.grails.plugins:audit-logging:2.0.1'.

2016-08-25 14:46 GMT+02:00 Robert Oschwald <notifications@github.com>:

**Comment by robertoschwald** [comment]
Take a look to the audit-test sample test application. There I added a sample AuditTrail Controller and named queries to AuditTrail.
You can filter by date after in this sample application now. If you want to filter for a specific day / time, you must add 2 search fields (from / to) or you form your own date before performing the query.
