### ISSUE TITLE
TRUNCATE_LENGTH setting doesn´t to work in Grails 3.1.10 

### ISSUE THREAD

**Issue by mamagaal** [robertoschwald/grails-audit-logging-plugin#124]
Grails 3.1.10 with audit-log 2.0.1

Adding  grails.plugin.auditLog.TRUNCATE_LENGTH = 255 to my application.groovy file doesn´t seem to work as stated in the documentation. I have inspected the code but I don´t see where this setting is applied whereas I can locate the place in audit-log 1.x plugin. Wasn´t this feature ported to 2.x version?

**Comment by robertoschwald** [comment]
You do not need this setting in 2.0.1, as you must call audit-quickstart to create your own Domain class for AuditLogging. There, you set the attribute length in the constraints. See https://github.com/robertoschwald/grails-audit-logging-plugin/blob/master/audit-logging/src/main/templates/AuditLogEvent.groovy.template#L57

**Comment by mamagaal** [comment]
Ok, thank you
