### ISSUE TITLE
Audit for many-to-many collections

### ISSUE THREAD

**Issue by azhuchkov** [robertoschwald/grails-audit-logging-plugin#126]
Apparently current implementation (1.1.0) only supports one-to-many relationships audit:
```
// In some cases, collections aren't listed as being dirty in the dirty property names.
    // We need to check them individually.
    entity.associationMap.each { String associationName, value ->
      if (entity.isOneToMany(associationName)) {
        def collection = domain."${associationName}"
        if (collection?.respondsTo('isDirty') && collection?.isDirty()) {
          dirtyProperties << associationName
        }
      }
    }
```
Is it by design? There are many-to-many collections which i'd like to track. Something like:
```
static hasMany = [
  tags: String
]
```
This is a many-to-many relationship which is completely ignored by the plugin.

**Comment by robertoschwald** [comment]
Fixed with release 2.0.2

**Comment by azhuchkov** [comment]
Thank you! Could you please backport it to 1.x_maintenance branch for Grails 2.x? I was waiting this fix there :)

**Comment by robertoschwald** [comment]
Hold on, working on it.

**Comment by robertoschwald** [comment]
1.1.1 Released. Please test.

**Comment by azhuchkov** [comment]
It works. Thanks!
