### ISSUE TITLE
Externalize AuditTrailEvent domain to user

### ISSUE THREAD

**Issue by dmahapatro** [robertoschwald/grails-audit-logging-plugin#13]
Configure to externalize `AuditTrailEvent` domain class to end user. This helps owner of the audit event table to customize it properties.

**Comment by robertoschwald** [comment]
Just a quick note: Domain name is AuditLogEvent. We should'nt change that in my opinion, otherwise everybody needs to migrate the db when upgrading. What do you think?

**Comment by dmahapatro** [comment]
Correct. My bad it is `AuditLogEvent`. But this can be made configurable for new users. Something similar to what lazybones does. This can be part of future backlog.

**Comment by robertoschwald** [comment]
For documentation: The AuditLogEvent domain class is currently embedded in the plugin. As we added many configuration settings  (mapping, id-generation, etc), this needed some undocumented workarounds (e.g. id is of type "Object", as it can be String, Long, etc. dependent on the mapping config. This has side-effects we want to eliminate. This change is scheduled for the Grails 3.0 release.

**Comment by dmahapatro** [comment]
@robertoschwald I totally forgot to mention that I am on the path of converting this plugin to Grails 3 version. I am half way through and fixing the integration tests. I have create a new branch `grails3` and will push it my remote. You will see a PR coming in the near future. Let me know if the plan sounds good.

Nothing extra is done during the conversion. I am just making sure that I move the code as is, make it compatible with Grails 3, make it functional and release. Once released we can optimize the functionality. What do you say?

**Comment by robertoschwald** [comment]
Graeme just sent a PR for Grails 3 migration. See #15

**Comment by dmahapatro** [comment]
@robertoschwald Did not realize Graeme has already [done the conversion](https://github.com/robertoschwald/grails-audit-logging-plugin/pull/15). LOL I was in the same path. :)

**Comment by robertoschwald** [comment]
I've initially implemented externalization in branch feature_1.x/externalizeALE1.x. 
All tests pass so far. 

However, I received weird AST exceptions if I try to obtain the configured AuditLogEvent domain class from ApplicationContext.getDomainClass() (Using ReflectionUtils.getAuditClass()) and call <AuditLogEventDomainClass>.where{} clauses in the tests.

Error is: 

    org.hibernate.hql.ast.QuerySyntaxException: unexpected AST node: 
    query [DELETE test.MyAuditLogEvent myAuditLogEvent WHERE ()]

 Any idea what causes this?

The plugin is configured the same way as spr-sec-core and many others, using 

    audit-quickstart <package_name> <AuditLogEventDomainClassName>

For now I didn't add a DefaultAuditLogEvent class as fallback, as I do not want to maintain the ugly domain-class configuration stuff anymore. 

Would be great if you get a chance to review and test in one of your projects. Thx.

**Comment by robertoschwald** [comment]
Note: This change is for Grails 2.x plugin version 1.x. I implemented it first for this plugin branch, as we need it for #93 (as mongodb plugin does not use the mapping {datasource mongo} clause but the static "mapWith" field to select the DataSource to use, which is normally used in Grails to disable persistence...

**Comment by robertoschwald** [comment]
When we finish this implementation, I will release version 1.8 (and update the Plugin docs). Afterwards, I implement on master for Grails 3.

**Comment by robertoschwald** [comment]
Published 1.1.0-SNAPSHOT with externalized AuditLogEvent domain class support. Would be great if you can test it.

**Comment by robertoschwald** [comment]
Report from bronoman in #103 : 

Thanks for the new SNAPSHOT and the MongoDB sample link. Extremely helpful. Looks like there is still a minor problem with the audit-quickstart script, the stacktrace is:

```
| Error Error executing script AuditQuickstart: 
org/codehaus/groovy/grails/plugins/orm/auditable/AuditLoggingUtils (NOTE: Stack trace has been filtered.[...]
trace.)
java.lang.NoClassDefFoundError: org/codehaus/groovy/grails/plugins/orm/auditable/AuditLoggingUtils
at AuditQuickstart$_updateConfig_closure2.doCall(AuditQuickstart:90)
at AuditQuickstart.updateConfig(AuditQuickstart:86)
at AuditQuickstart.this$4$updateConfig(AuditQuickstart)
at org.codehaus.gant.GantMetaClass.invokeMethod(GantMetaClass.java:133)
at [...........]
```

However, after adding the new config parameter manually to my Config.groovy like:
auditDomainClassName = "com.example.myApp.AuditLogEvent"
my application started up correctly and the external domain class seems to work fine.

**Comment by robertoschwald** [comment]
1.1.0-SNAPSHOT2 published which fixes the NoClassDefFoundError in the GANT script

**Comment by betsonc** [comment]
Hi, using Grails 3.1.4 and audit-logging:2.0.1 I get the error below
We use application.yml if this makes a difference.  Can we have application.yml and application.groovy together?

Any ideas what is causing it? 
Many Thanks

Error creating bean with name 'grails.plugins.orm.auditable.AuditLogEventController': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: 

Could not autowire method: public void grails.plugins.orm.auditable.AuditLogEventController.setTagLibraryLookup(org.grails.taglib.TagLibraryLookup); 
nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: 
No qualifying bean of type [org.grails.taglib.TagLibraryLookup] found for dependency: 
expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {}
