### ISSUE TITLE
Integration test fails on grails 3.2.5

### ISSUE THREAD

**Issue by igalmarino** [robertoschwald/grails-audit-logging-plugin#131]
Today i upgraded to grails 3.2.5 and now my integration tests are failing with this error:

java.lang.IllegalStateException: No value for key [org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy@ccb72fb] bound to thread [Test worker]

if i downgrade to grails 3.2.4 everything is working fine.

- grails 3.2.5
- audit-logging 2.0.3
- testing DB: H2
- transactional = false (default)

**Comment by robertoschwald** [comment]
Have you got multiple datasources defined? 
Can you provide a full stacktrace or sample application which fails?

**Comment by igalmarino** [comment]
I do not have multipe datasources

sample application: https://bitbucket.org/arkkosoft/test

**Comment by igalmarino** [comment]
it is working again on grails 3.2.6

**Comment by robertoschwald** [comment]
Grails Issue: https://github.com/grails/grails-core/issues/10459
