### ISSUE TITLE
Audit plugin unable to process delete event for ...

### ISSUE THREAD

**Issue by meltzow** [robertoschwald/grails-audit-logging-plugin#132]
the exception is thrown in AuditLogListener while deleting a object. 
we using plugin version 1.1.1 with grails 2.4.5

The problem is, the interface GrailsApplication (or do be more specific - the implementation of the interface) doesn't have a method named "isDomainClass".
this is used in AuditLogListenerUtil.groovy in line 139. 
thx.

**Comment by robertoschwald** [comment]
Which exception? Stacktrace?

isDomainClass is a dynamic method defined in DomainClassArtefactHandler.isDomainClass()

**Comment by meltzow** [comment]
Sorry: 
ERROR auditable.AuditLogListener  - Audit plugin unable to process delete event for wms.warenausgang.WarenausgangPosition: 
Message: null
    Line | Method
->>  111 | initializeCollectionFromCache   in org.hibernate.event.def.DefaultInitializeCollectionEventListener
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     71 | onInitializeCollection          in     ''
|   1863 | initializeCollection . . . . .  in org.hibernate.impl.SessionImpl
|    369 | initialize                      in org.hibernate.collection.AbstractPersistentCollection
|    111 | read . . . . . . . . . . . . .  in     ''
|    186 | iterator                        in org.hibernate.collection.PersistentSet
|   1372 | each . . . . . . . . . . . . .  in org.codehaus.groovy.runtime.DefaultGroovyMethods
|     -1 | invoke                          in org.codehaus.groovy.runtime.dgm$149
|    271 | invoke . . . . . . . . . . . .  in org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce
|     53 | call                            in org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite
|    116 | call . . . . . . . . . . . . .  in org.codehaus.groovy.runtime.callsite.AbstractCallSite
|    622 | truncate                        in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener
|     -1 | callCurrent . . . . . . . . . . in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener$truncate$5
|     49 | defaultCallCurrent              in org.codehaus.groovy.runtime.callsite.CallSiteArray
|     -1 | callCurrent . . . . . . . . . . in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener$truncate$5
|    605 | conditionallyMaskAndTruncate    in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener
|     -1 | invoke . . . . . . . . . . . .  in sun.reflect.GeneratedMethodAccessor1794
|     43 | invoke                          in sun.reflect.DelegatingMethodAccessorImpl
|    498 | invoke . . . . . . . . . . . .  in java.lang.reflect.Method
|   1276 | jlrMethodInvoke                 in org.springsource.loaded.ri.ReflectiveInterceptor
|     90 | invoke . . . . . . . . . . . .  in org.codehaus.groovy.reflection.CachedMethod
|    324 | doMethodInvoke                  in groovy.lang.MetaMethod
|   1206 | invokeMethod . . . . . . . . .  in groovy.lang.MetaClassImpl
|   1120 | invokeMethod                    in groovy.lang.ExpandoMetaClass
|   1015 | invokeMethod . . . . . . . . .  in groovy.lang.MetaClassImpl
|   1151 | invokeMethod                    in     ''
|   1120 | invokeMethod . . . . . . . . .  in groovy.lang.ExpandoMetaClass
|   1015 | invokeMethod                    in groovy.lang.MetaClassImpl
|     66 | callCurrent . . . . . . . . . . in org.codehaus.groovy.runtime.callsite.PogoMetaClassSite
|    149 | callCurrent                     in org.codehaus.groovy.runtime.callsite.AbstractCallSite
|    558 | doCall . . . . . . . . . . . .  in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener$_logChanges_closure10
|     -2 | invoke0                         in sun.reflect.NativeMethodAccessorImpl
|     62 | invoke . . . . . . . . . . . .  in     ''
|     43 | invoke                          in sun.reflect.DelegatingMethodAccessorImpl
|    498 | invoke . . . . . . . . . . . .  in java.lang.reflect.Method
|   1276 | jlrMethodInvoke                 in org.springsource.loaded.ri.ReflectiveInterceptor
|     90 | invoke . . . . . . . . . . . .  in org.codehaus.groovy.reflection.CachedMethod
|    324 | doMethodInvoke                  in groovy.lang.MetaMethod
|   1206 | invokeMethod . . . . . . . . .  in groovy.lang.MetaClassImpl
|   1120 | invokeMethod                    in groovy.lang.ExpandoMetaClass
|   1015 | invokeMethod . . . . . . . . .  in groovy.lang.MetaClassImpl
|    423 | call                            in groovy.lang.Closure
|   4271 | callClosureForMapEntry . . . .  in org.codehaus.groovy.runtime.DefaultGroovyMethods
|   1408 | each                            in     ''
|     -1 | invoke . . . . . . . . . . . .  in org.codehaus.groovy.runtime.dgm$151
|    271 | invoke                          in org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce
|     53 | call . . . . . . . . . . . . .  in org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite
|    116 | call                            in org.codehaus.groovy.runtime.callsite.AbstractCallSite
|    549 | logChanges . . . . . . . . . .  in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener
|     -1 | callCurrent                     in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener$logChanges$2
|     49 | defaultCallCurrent . . . . . .  in org.codehaus.groovy.runtime.callsite.CallSiteArray
|     -1 | callCurrent                     in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener$logChanges$2
|    300 | onPreDelete . . . . . . . . . . in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener
|     -2 | invoke0                         in sun.reflect.NativeMethodAccessorImpl
|     62 | invoke . . . . . . . . . . . .  in     ''
|     43 | invoke                          in sun.reflect.DelegatingMethodAccessorImpl
|    498 | invoke . . . . . . . . . . . .  in java.lang.reflect.Method
|   1276 | jlrMethodInvoke                 in org.springsource.loaded.ri.ReflectiveInterceptor
|    166 | invoke . . . . . . . . . . . .  in org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSite
|     56 | callCurrent                     in org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite
|    141 | callCurrent . . . . . . . . . . in org.codehaus.groovy.runtime.callsite.AbstractCallSite
|    108 | onPersistenceEvent              in org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListener
|     47 | onApplicationEvent . . . . . .  in org.grails.datastore.mapping.engine.event.AbstractPersistenceEventListener
|     98 | multicastEvent                  in org.springframework.context.event.SimpleApplicationEventMulticaster
|    333 | publishEvent . . . . . . . . .  in org.springframework.context.support.AbstractApplicationContext
|    159 | publishEvent                    in org.codehaus.groovy.grails.orm.hibernate.support.ClosureEventTriggeringInterceptor
|    144 | onPreDelete . . . . . . . . . . in     ''
|    131 | preDelete                       in org.hibernate.action.EntityDeleteAction
|     71 | execute . . . . . . . . . . . . in     ''
|    273 | execute                         in org.hibernate.engine.ActionQueue
|    265 | executeActions . . . . . . . .  in     ''
|    189 | executeActions                  in     ''
|     46 | performExecutions . . . . . . . in org.codehaus.groovy.grails.orm.hibernate.events.PatchedDefaultFlushEventListener
|     51 | onFlush                         in org.hibernate.event.def.DefaultFlushEventListener
|   1216 | flush . . . . . . . . . . . . . in org.hibernate.impl.SessionImpl
|    383 | managedFlush                    in     ''
|    133 | commit . . . . . . . . . . . .  in org.hibernate.transaction.JDBCTransaction
|    662 | doCommit                        in org.springframework.orm.hibernate3.HibernateTransactionManager
|    757 | processCommit . . . . . . . . . in org.springframework.transaction.support.AbstractPlatformTransactionManager
|    726 | commit                          in     ''
|    478 | commitTransactionAfterReturning in org.springframework.transaction.interceptor.TransactionAspectSupport
|    272 | invokeWithinTransaction         in     ''
|     95 | invoke . . . . . . . . . . . .  in org.springframework.transaction.interceptor.TransactionInterceptor
|    179 | proceed                         in org.springframework.aop.framework.ReflectiveMethodInvocation
|    644 | intercept . . . . . . . . . . . in org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor
|     -1 | loeschen                        in wms.warenausgang.WarenausgangService$$EnhancerBySpringCGLIB$$333fda96
|     45 | defaultCall . . . . . . . . . . in org.codehaus.groovy.runtime.callsite.CallSiteArray

**Comment by robertoschwald** [comment]
Can you provide a standard stacktrace? I don't see the root cause in your log, and it's hard to read, too.

**Comment by meltzow** [comment]
I dont know what you mean with: "standard stacktrace". I copied this from my eclipse console.  
bye, the way, its not a throw exception. you catch the exception and you do a log.error "Audit plugin unable to process delete event for ${domain.class.name}: ", e

 your code in AuditLogListener


` protected void onPreDelete(PreDeleteEvent event) {

    def domain = event.entityObject

    try {
      def entity = getDomainClass(domain)

	  if(ignoreEvent(domain, "onDelete")) {
		  return
	  }
	  
	  def map = makeMap(entity.persistentProperties*.name as Set, domain)
      if (!callHandlersOnly(domain)) {
        if (nonVerboseDelete) {
          log.debug("Forced Non-Verbose logging by config onPreDelete.")
          withoutVerboseAuditLog {
            logChanges(domain, null, map, getEntityId(domain), getEventName(event), getClassName(entity))
          }
        } else {
          logChanges(domain, null, map, getEntityId(domain), getEventName(event), getClassName(entity))
        }
      } else {
        def identifier = entity.identifier.name
        if (!map.containsKey(identifier) && domain."$identifier") {
          map << [(identifier): domain."$identifier"]
        }
      }
      executeHandler(domain, 'onDelete', map, null)
    }
    catch (e) {
      log.error "Audit plugin unable to process delete event for ${domain.class.name}: ", e
    }
  }`

**Comment by meltzow** [comment]
any news here?

**Comment by meltzow** [comment]
the problem is the method getEntityId is used in AudiLogListener but is not defined here.

**Comment by meltzow** [comment]
ahh, you use a static import from org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogListenerUtil.*
but it seems, its not working.

**Comment by robertoschwald** [comment]
Can you provide a sample project showing the error? We never had such a report before, therefore we cannot see what the root cause of the exception is. Which Environment do you use (Java, Grails, Hibernate, etc.)?

**Comment by meltzow** [comment]
we are using java openjdk version "1.8.0_121" and grails 2.4.5 with mysql.

**Comment by robertoschwald** [comment]
Which Hibernate version?

**Comment by meltzow** [comment]
hibernate:3.6.10.18

**Comment by robertoschwald** [comment]
A small sample project would be great to analyse this. Can you provide one?

**Comment by meltzow** [comment]
Its not fixed.

**Comment by robertoschwald** [comment]
I requested a sample project from you. We cannot reproduce the issue so we don't know how to help further.
