### ISSUE TITLE
ignore config option not respected for INSERT and DELETE events

### ISSUE THREAD

**Issue by jglapa** [robertoschwald/grails-audit-logging-plugin#143]
`ignore` fields config option is not respected upon saving and deleting objects.

Can we add such feature or this cannot be done for some reason?

My use case is that I store a bit of binary data in one of my domains and I'm not interested in tracking that field content **at all**

I would be happy to contribute if this would be accepted as feature.

**Comment by robertoschwald** [comment]
Which plugin version? For 1.x it is already fixed with #136 and needs backport to 2.x. See #144

**Comment by jglapa** [comment]
Ah yes, I forgot to mention the version number it's the `2.0.4` but I also tried it on `1.0.6` and it didn't work. (I'm in process of migrating to Grails3).
Any way this explains everything. 
Any timing around backporting this?

**Comment by robertoschwald** [comment]
Currently on it.

**Comment by robertoschwald** [comment]
Closing this duplicate. See #144
