### ISSUE TITLE
Could not find artifact org.grails.plugins:audit-logging:jar:1.1.3

### ISSUE THREAD

**Issue by amankm** [robertoschwald/grails-audit-logging-plugin#157]
Why do I get this error message? 

>  Could not find artifact org.grails.plugins:audit-logging:jar:1.1.3 in grailsCentral (https://repo.grails.org/grails/plugins)

I am using grails 2.5.4

**Comment by robertoschwald** [comment]
Check your repo settings. Plugin is in the repo. https://repo.grails.org/grails/plugins/org/grails/plugins/audit-logging/1.1.3/.

**Comment by amankm** [comment]
@robertoschwald - Thanks  for your time. I had made a silly mistake. I had happened to add it in "dependencies" section instead of "plugins".
