### ISSUE TITLE
Stamp fields should be at the end.

### ISSUE THREAD

**Issue by aadrian** [robertoschwald/grails-audit-logging-plugin#158]
Please place the stamp fields always at the end of the entity (and DDL),
and also in the same predictable order.

Thank you.

**Comment by longwa** [comment]
I'm not sure how we could control this via the Trait. The stamp fields would need to be added by a database migration so couldn't it just put them at the end?

**Comment by robertoschwald** [comment]
Thats correct. Its up to the implementor to define the order, e.g. by reordering the migration.
