### ISSUE TITLE
Grails 3.3.x Support

### ISSUE THREAD

**Issue by robertoschwald** [robertoschwald/grails-audit-logging-plugin#161]
- Rewrite plugin to use CompileStatic where possible
- Use Traits instead of AST Transformations
- Cleanup code
- Remove Handler support (users can use the GORM events directly in their Domain classes)

**Comment by sudosandwich3** [comment]
Hey, What still needs to be done to upgrade the plugin to 3.3.x?  Is there a road map, or any opportunities to submit PRs?

**Comment by longwa** [comment]
@robertoschwald The changes I made already support 3.3.x and we are using it today with 3.3.6 and GORM 6.1.10.

I think we just need to officially release my Trait rewrite.

**Comment by longwa** [comment]
@sudosandwich3 Take a look at the docs at https://robertoschwald.github.io/grails-audit-logging-plugin/snapshot/plugin.html. 

The current master branch is 3.0.0-SNAPSHOT and is a large rewrite of the API but works with Grails 3.3.x. The migration isn't too difficult and the docs should explain the main changes.

I would also like to see the official 3.0.0 version released.

**Comment by longwa** [comment]
Crap, looks like the documentation formatting has gotten messed up at some point along the way. I'll try to push a change to clean it up.

**Comment by robertoschwald** [comment]
@longwa Goodto know it works with 3.3.6 as well. I will bake a release then.

**Comment by longwa** [comment]
@robertoschwald I pushed a change to fix the documentation formatting issue and remove the references to the Stamp support (I think Dennie pulled that stuff into a separate plugin). I'm not sure how you were publishing the docs but if you pull now and regenerate it should be good.

**Comment by robertoschwald** [comment]
Thanks for the change. Plugin is still supporting Stampable. Dennie has started PR #167 which is not finished, yet. I revert the doc files for Stampable refs.

**Comment by robertoschwald** [comment]
Need to migrate gradle build file for grailsPublish plugin, also.
