### ISSUE TITLE
Version 3.0.0 totally breaks even trivial applications.

### ISSUE THREAD

**Issue by aadrian** [robertoschwald/grails-audit-logging-plugin#169]
`grails-audit-logging-plugin` version 3.0.0 seems to totally break even trivial Grails 3.3.5 applications :( .

Please see in this small example: https://github.com/aadrian/grenderingz/tree/audit_logging

After adding the plug-in, nothing works anymore https://github.com/aadrian/grenderingz/commit/44eb3269586530291d58545fe261deaadde27153  :( .

Following the documentation and how this version of the plug-in it's supposed to be different from version 2.x, those are the only changes made that are visible in that commit diff. 

Am I missing something? Or is the plug-in indeed broken with Grails 3.3.5?

Thank you.

**Comment by robertoschwald** [comment]
I don't know whats your problem, as you didn't state it. Here, your example runs...?
```
[grenderingz master]$ gradle clean
gradlew: Permission denied
gradlew: cannot execute: Undefined error: 0
[grenderingz master]$ chmod 755 gradlew
[grenderingz master*]$ chmod 755 grailsw
[grenderingz master*]$ grails run-app
Using grailsw
| Resolving Dependencies. Please wait...
Download https://repo.grails.org/grails/core/org/grails/plugins/views-gradle/1.2.8/views-gradle-1.2.8.pom
Download https://repo.grails.org/grails/core/org/grails/plugins/views-gradle/1.2.8/views-gradle-1.2.8.jar
Download https://repo.grails.org/grails/core/org/grails/plugins/views-json/1.2.8/views-json-1.2.8.pom
Download https://repo.grails.org/grails/core/org/grails/views-core/1.2.8/views-core-1.2.8.pom
Download https://repo.grails.org/grails/core/org/grails/plugins/views-json/1.2.8/views-json-1.2.8.jar
Download https://repo.grails.org/grails/core/org/grails/views-core/1.2.8/views-core-1.2.8.jar

CONFIGURE SUCCESSFUL

| Running application...
--> Init application ....
-->  ... Initializing data, since the DB was empty ...
--> Init application DONE!
Grails application running at http://localhost:8080 in environment: development
```

**Comment by robertoschwald** [comment]
Ah, I see. In your example, audit-logging is not included at all.

**Comment by longwa** [comment]
I’ll take a look. We are using the plugin in a very large 3.3.6 application with dozens of audited domains and dependencies.

**Comment by longwa** [comment]
The https://github.com/robertoschwald/grails-audit-logging-plugin/pull/170 should fix this issue. I used the sample app in this ticket to verify the changes.

**Comment by robertoschwald** [comment]
Please use Version 3.0.1

**Comment by aadrian** [comment]
@robertoschwald @longwa yes, with 3.0.1 it works again :) . 
Thank you for the update!
