### ISSUE TITLE
Different timestamps when inserting an entity!

### ISSUE THREAD

**Issue by eprozium** [robertoschwald/grails-audit-logging-plugin#171]
When inserting an entity, the audit log table will have more rows (one per non-excluded field).
The timestamp is different (`create_date`) , and this makes it very hard to track changes.

Please fix it, so that for one operation, the same timestamp is used.

Thanks.

**Comment by robertoschwald** [comment]
We could set it anyway and add autoTimestamp false to our entity template. 

It's then up to the users to disable autoTimestamp in their already existing Domain class if they want to have the same create date. 

We can document this in the upgrade doc.

**Comment by eprozium** [comment]
@longwa @robertoschwald yes, that would be great, but the `audit-quickstart` should also generate it correctly.

**Comment by longwa** [comment]
@robertoschwald Agreed. I'm making that change now.

**Comment by longwa** [comment]
I'll let this run in our application for a couple of days to verify and then open the PR for #171, #172, and #173.
