### ISSUE TITLE
AuditLogEvent is private in controller.

### ISSUE THREAD

**Issue by eprozium** [robertoschwald/grails-audit-logging-plugin#172]
The `AuditLogEvent` is now private in https://github.com/robertoschwald/grails-audit-logging-plugin/blob/master/plugin/grails-app/controllers/grails/plugins/orm/auditable/AuditLogEventController.groovy#L22
so code that was extending that controller will break (e.g. with Grails 2.x)

Please change it to public, **or** mention it in the documentation https://robertoschwald.github.io/grails-audit-logging-plugin/latest/plugin.html#upgrading upgrading section too.

Thanks.

**Comment by longwa** [comment]
That was to ensure that it wasn't exposed as a controller action. What if I made it protected instead so that you could still extend it?
