### ISSUE TITLE
grails4.0.0RC1(rest-api) and audit-logging3.0.4 running error

### ISSUE THREAD

**Issue by zhangjiayu139** [robertoschwald/grails-audit-logging-plugin#186]
版本：org.grails.plugins：audit-logging：3.0.4 and grails4.0.0RC1
my Problem : I don't know, document code means:

![image](https://user-images.githubusercontent.com/30860538/58793636-225fde00-8629-11e9-8f2a-f303f130b699.png)
and my Code:
![image](https://user-images.githubusercontent.com/30860538/58793732-5b984e00-8629-11e9-80a7-ee0ca5b10360.png)
![image](https://user-images.githubusercontent.com/30860538/58793766-7074e180-8629-11e9-8918-b290cf436050.png)
I don't know 'customService = ref('customService')' what's means? give me code is very very very best(or demo or code)

**Comment by robertoschwald** [comment]
1. Why do you wire in the SpringSecurityRequestResolver as "springSecurityRequestResolver"? The resolvers ALWAYS must be wired in with bean name "auditRequestResolver". The SpringSecurityRequestResolver is wired in automatically when spring-security-core plugin is detected. 

So to use your request resolver, you must register as "auditRequestResolver":
```
beans = {
   auditRequestResolver(CustomAuditRequestResolver)
}
```

2. This is an issue tracker for bugs and enhancements, not a support forum. Please use the Grails Slack Channel.

**Comment by zhangjiayu139** [comment]
Thank you very, very much for your answer,I made the same mistake the way you wrote it，
