### ISSUE TITLE
Could not find artifact org.grails.plugins:audit-logging:jar:1.1.3 in grailsCentral (http://repo.grails.org/grails/plugins)

### ISSUE THREAD

**Issue by asuraphel** [robertoschwald/grails-audit-logging-plugin#196]
I've added:

```
dependencies {

    compile 'org.grails.plugins:audit-logging:1.1.3'


   ....
}
```
And the dependency is right at http://repo.grails.org/grails/plugins/org/grails/plugins/audit-logging/1.1.3/

`compile 'org.grails.plugins:audit-logging:2.0.6'` works though. 

My Grails version is 2.3.11.

**Comment by asuraphel** [comment]
Putting the dependency on `plugins` instead of `dependencies` block worked. This is not mentioned on the documentation.

**Comment by robertoschwald** [comment]
It _is_ documented on the 2.x plugin page:
```
Installation
Install as **plugin** dependency in BuildConfig.groovy (see above).
If you use Grails < 2.0, perform:
```
