### ISSUE TITLE
NoSuchBeanDefinitionException thrown in unit tests

### ISSUE THREAD

**Issue by andrewcanby-finocomp** [robertoschwald/grails-audit-logging-plugin#203]
### Task List
- [x]  Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem uploaded to Github
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

1. Add `Auditable` to a domain
2. Implement/override the `clone()` method for a domain, selectively omitting properties
3. Unit test the `clone` method and see the exception

Full details in linked example application.

### Expected Behaviour

An exception should not be thrown when there is no `AuditRequestResolver` bean provided, instead the default fallback behaviour should be used (a default String etc.)

### Actual Behaviour

While unit testing `myDomainInstance.clone()` a `NoSuchBeanDefinitionException` is thrown once `Auditable` is added to the Domain class. Note that this is not the only time it is an issue, but the simplest way to reproduce.

This will likely only manifest as a test issue, given the plugin explicitly registers the bean on application startup.

### Environment Information

- **Operating System**: Mac 10.15.5
- **GORM Version:** 7.0.4.RELEASE
- **Grails Version (if using Grails):** 4.0.3
- **JDK Version:** 8.0.252-zulu

### Example Application

https://github.com/andrewcanby-finocomp/audit-bean-in-tests

**Comment by robertoschwald** [comment]
Thanks for the report. Will look into it.
