### ISSUE TITLE
GPAUDITLOGGING-50: Log old collection values

### ISSUE THREAD

**Issue by robertoschwald** [robertoschwald/grails-audit-logging-plugin#42]
Original Reporter: roos
Environment: Not Specified
Version: Grails-AuditLogging 1.0.0
Migrated From: http://jira.grails.org/browse/GPAUDITLOGGING-50

With 1.0.0, we will be ORM implementation agnostic and will not depend on Hibernate anymore.

GrailsDomainClass currently does not support getting old value for collections as Hibernate supports with snapshots (which we used in the 0.5.x plugin versions).

We need to find a way to get the old value of collections.

**Comment by k11i** [comment]
Is there already some improvement on this subject?

We would like to use this plugin to log the changes in our project but not being able to see what was changed within a collection might be a show stopper for us.

**Comment by robertoschwald** [comment]
Not yet.

**Comment by zackd** [comment]
Was this fixed? I'm still seeing this problem in 4.0.3 with Grails 5.2.5
