### ISSUE TITLE
https://jira.grails.org/browse/GRAILS-9375

### ISSUE THREAD

**Issue by B5A7** [robertoschwald/grails-audit-logging-plugin#94]
Hi

I am getting this error when using the plugin:

Error |
2015-07-21 10:07:38,165 [http-bio-8080-exec-6] ERROR errors.GrailsExceptionResolver  - TypeMismatchException occurred when processing request: [GET] /psav2/auditLogEvent/show/2
Provided id of the wrong type for class org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogEvent. Expected: class java.lang.Long, got class java.lang.String. Stacktrace follows:
Message: Provided id of the wrong type for class org.codehaus.groovy.grails.plugins.orm.auditable.AuditLogEvent. Expected: class java.lang.Long, got class java.lang.String
    Line | Method
->>  198 | doFilter  in grails.plugin.cache.web.filter.PageFragmentCachingFilter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     63 | doFilter  in grails.plugin.cache.web.filter.AbstractFilter
|     53 | doFilter  in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|     49 | doFilter  in grails.plugin.springsecurity.web.authentication.RequestHolderAuthenticationFilter
|     82 | doFilter  in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|   1145 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    615 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

Seems strange because I haven't done anything to modify the generic behavior of the plugin.  Any ideas.

Thanks
Brad

**Comment by dmahapatro** [comment]
What is the implementation in the controller for `/psav2/auditLogEvent/show/2`. Most likely the query on `AuditLogEvent` directly uses the `id` from url parameter, hence String.

Try casting it to long before querying `AuditLogEvent` table.

**Comment by robertoschwald** [comment]
Which version are you using?

Sent while mobile.

**Comment by robertoschwald** [comment]
Similiar issue was fixed in 1.0.5, so I assume you use an older version.

**Comment by robertoschwald** [comment]
Look into the actual source of [AuditLogEventController](https://github.com/robertoschwald/grails-audit-logging-plugin/blob/master/audit-logging/grails-app/controllers/grails/plugins/orm/auditable/AuditLogEventController.groovy#L42). You must perform auditLogEvent = AuditLogEvent.get(params.long('id')), as automatic type conversion does not work here, as the id in AuditLogEvent is now of type Object. This is a current limitation as some wanted to use configurable UUID id's, therefore we needed to change to Object. 

Try it out.

**Comment by robertoschwald** [comment]
Workaround provided. We are working on #13 so you get full control of the AuditLogEvent domain class in the future.
