### ISSUE TITLE
Retrieve Stored object log?

### ISSUE THREAD

**Issue by confile** [robertoschwald/grails-audit-logging-plugin#95]
Logging works great. But I do not see any helper to get the stored object back. Do I have to write it myself?

**Comment by robertoschwald** [comment]
There is a minimalistic controller provided by the plugin, mapped to uri /auditLogEvent by default.

You can look into the Controller sources to get an idea. It's pretty much default gorm used there.

**Comment by confile** [comment]
Okay, I thought you might have other options.
