### ISSUE TITLE
Using Oracle Database 11g with "largeValueColumnTypes=true" property, it fails to create AUDIT_LOG table

### ISSUE THREAD

**Issue by ignaciobayetto** [robertoschwald/grails-audit-logging-plugin#98]
Using v1.0.5 of the plugin and Oracle Database 11g Enterprise Edition Release 11.2.0.4.0 - 64bit Production, when I run this configuration: 

My Config.groovy: 

auditLog {
  verbose = true 
  logIds = true
  largeValueColumnTypes = true // use large column db types for oldValue/newValue.
  TRUNCATE_LENGTH = 1000
  cacheDisabled = true
  logFullClassName = true
  actorClosure = { request, session ->
    org.apache.shiro.SecurityUtils.getSubject()?.getPrincipal()
  }
  stampEnabled = true
  stampAlways = false
  stampCreatedBy = 'createdBy' 
  stampLastUpdatedBy = 'lastUpdatedBy' 
}

I get this error: 

015-07-30 12:08:26,571 [localhost-startStop-1] INFO  hbm2ddl.TableMetadata  - HHH000126: Indexes: []
| Error 2015-07-30 12:08:26,640 [localhost-startStop-1] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create table AUDIT_LOG (id number(19,0) not null, actor varchar2(255 char), class_name varchar2(255 char), date_created timestamp not null, event_name varchar2(255 char), last_updated timestamp not null, new_value long, old_value long, persisted_object_id varchar2(255 char), persisted_object_version number(19,0), property_name varchar2(255 char), uri varchar2(255 char), primary key (id))
| Error 2015-07-30 12:08:26,641 [localhost-startStop-1] ERROR hbm2ddl.SchemaUpdate  - ORA-01754: una tabla sólo puede contener una columna del tipo LONG

Searching Oracle documentation I found that: 

ORA-01754:     a table may contain only one column of type LONG
Cause:     An attempt was made to add a LONG column to a table which already had a LONG column. Note that even if the LONG column currently in the table has already been marked unused, another LONG column may not be added until the unused columns are dropped.
Action:     Remove the LONG column currently in the table by using the ALTER TABLE command.

Note that the fields : new_value , old_value , are converted to Long when property largeValueColumnTypes is set true. 

Any ideas to fix this error ??

**Comment by robertoschwald** [comment]
Best is to use db-migration plugin for database changes. Oracle does not support 2 LONG columns. See similiar issue http://legacy.community.bonitasoft.com/groups/installation-5x/resolved-ora-01754-using-bundle-install-bos-551-tomcat-6032
